CREATE TABLE `fraudAuditLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`loanApplicationId` int NOT NULL,
	`userId` int NOT NULL,
	`fraudScore` int NOT NULL,
	`fraudFlags` text NOT NULL,
	`ssnDuplicate` int NOT NULL DEFAULT 0,
	`invalidSSNPattern` int NOT NULL DEFAULT 0,
	`invalidPhonePattern` int NOT NULL DEFAULT 0,
	`disposableEmail` int NOT NULL DEFAULT 0,
	`recentApplication` int NOT NULL DEFAULT 0,
	`highLoanLeverageRatio` int NOT NULL DEFAULT 0,
	`recentBankruptcy` int NOT NULL DEFAULT 0,
	`adminReview` enum('pending','approved','rejected','manual_review') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`adminReviewedBy` int,
	`finalDecision` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`detectedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `fraudAuditLog_id` PRIMARY KEY(`id`),
	KEY `fraudAuditLog_loanApplicationId_idx` (`loanApplicationId`),
	KEY `fraudAuditLog_userId_idx` (`userId`),
	KEY `fraudAuditLog_fraudScore_idx` (`fraudScore`),
	KEY `fraudAuditLog_adminReview_idx` (`adminReview`)
);
